[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:xvfb]
command=/opt/scripts/start-xvfb.sh
autorestart=true
priority=10
stdout_logfile=/var/log/xvfb.log
stderr_logfile=/var/log/xvfb.err

[program:desktop]
command=/opt/scripts/start-desktop.sh
autorestart=true
priority=20
stdout_logfile=/var/log/desktop.log
stderr_logfile=/var/log/desktop.err

[program:vnc]
command=/opt/scripts/start-vnc.sh
autorestart=true
priority=30
stdout_logfile=/var/log/vnc.log
stderr_logfile=/var/log/vnc.err

[program:novnc]
command=/opt/scripts/start-novnc.sh
autorestart=true
priority=40
stdout_logfile=/var/log/novnc.log
stderr_logfile=/var/log/novnc.err

[program:apps]
command=/opt/scripts/app-supervisor.sh
autorestart=true
priority=50
stdout_logfile=/var/log/apps.log
stderr_logfile=/var/log/apps.err

[program:ttyd]
command=/opt/scripts/start-ttyd.sh
autorestart=true
priority=60
stdout_logfile=/var/log/ttyd.log
stderr_logfile=/var/log/ttyd.err

[program:term-agent]
command=/opt/scripts/start-term-agent.sh
autorestart=true
priority=70
stdout_logfile=/var/log/term-agent.log
stderr_logfile=/var/log/term-agent.err
